### ISSUE TITLE
关于 独立性 是否可以多说一点？ 208.md

### ISSUE THREAD

**Issue by lambdaplus** [qiwsir/StarterLearningPython#100]
>这个例子说明，在实例化之后，实例变量girl传给个self。但是，提醒读者，千万不要用上面的修改了的那个方式。因为那样写使类没有独立性，这是大忌。

这个例子说明，在实例化之后，实例变量girl传给个self。但是，提醒读者，千万不要用上面的修改了的那个方式。因为那样写使类没有独立性，那个类就只能被实例化成名为girl的变量，若是想要实例化为boy就会报错，这是大忌。

-----
这样是更直白点呀还是啰嗦呀，齐老师。

**Comment by qiwsir** [comment]
ok，我再思考一下，怎样阐述更好，谢谢。

在 2016年5月7日 下午4:48，lambdaplus <notifications@github.com>写道：

> 这个例子说明，在实例化之后，实例变量girl传给个self。但是，提醒读者，千万不要用上面的修改了的那个方式。因为那样写使类没有独立性，这是大忌。
>
>
> 这个例子说明，在实例化之后，实例变量girl传给个self。但是，提醒读者，千万不要用上面的修改了的那个方式。因为那样写使类没有独立性，那个类就只能被实例化成名为girl的变量，若是想要实例化为boy就会报错，这是大忌。
> ------------------------------
>
> 这样是更直白点呀还是啰嗦呀，齐老师。
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/issues/100>
>



-- 
*QiWei*
