### ISSUE TITLE
209.md  调用覆盖方法  小节中的表述问题。

### ISSUE THREAD

**Issue by lambdaplus** [qiwsir/StarterLearningPython#103]
class Girl(Person):
        def __init__(self, name):
            #Person.__init__(self, name)
            super(Girl, self).__init__(name)
            self.real_name = "Aoi sola"

        def get_name(self):
            return self.name

仅仅修改一处，将`Person.__init__(self, name)`去掉，修改为`super(Girl, self).__init__(name)`。实行程序后，显示的结果与以前一样。

---
仅仅修改一处，将`Person.__init__(self, name)`修改为`super(Girl, self).__init__(name)`。实行程序后，显示的结果与以前一样。

---
改成类似如上表述，是否更好一点呢？

**Comment by qiwsir** [comment]
好。谢谢。我去修改之。
