### ISSUE TITLE
109.md 问题

### ISSUE THREAD

**Issue by sunsulei** [qiwsir/StarterLearningPython#105]
你好！
感谢您的入门教程。
在109.md里
`>>> a = "qiwsir,python" 
>>> a.upper()       #将小写字母完全变成大写字母
'QIWSIR,PYTHON'
>>> a               #原数据对象并没有改变
'qiwsir,python'
>>> b = a.upper()
>>> b
'QIWSIR,PYTHON'
>>> c = b.lower()   #将所有的小写字母变成大写字母 **//这一行是不是写反了。应该是大写字母变成小写字母。新学者。**
>>> c
'qiwsir,python'

>>> a
'qiwsir,python'
>>> a.capitalize()  #把字符串的第一个字母变成大写
'Qiwsir,python'
>>> a               #原数据对象没有改变
'qiwsir,python'
>>> b = a.capitalize() #新建立了一个
>>> b
'Qiwsir,python'`
再次感谢。

**Comment by qiwsir** [comment]
b.lower()，将所有字母编程小写的。
