### ISSUE TITLE
French Navy last morse code message

### ISSUE THREAD

**Issue by codyli520** [qiwsir/StarterLearningPython#115]
在字符编码里法国海军的那段
>“所有人注意，这是我们在永远沉寂之前最后的一声呐喊！”

的摩斯电码难道不是？
> -.-. .- .-.. .-.. .. -. --./.- .-.. .-../- .... .. .../.. .../--- ..- .-. / .-.. .- ... - /-.-. .-. -.--/ -... . ..-. --- .-. ./ --- ..- .-. /. - . .-. -. .- .-../ ... .. .-.. . -. -.-. .

 所以也不能全信wikipedia

**Comment by qiwsir** [comment]
多谢。这个我不懂。多谢指点。
