### ISSUE TITLE
109.md-错别字纠正 即第一个参数传入的"pytohn"

### ISSUE THREAD

**Issue by HAOGRE** [qiwsir/StarterLearningPython#119]
format("python", "canglaoshi")是字符串格式化输出的方法，传入了两个字符串，它们分别对应这"I like {0} and {1}"里的那两个占位符，而且使按照顺序对应的，即第一个参数传入的"pytohn"，对应着{0}，第二参数传入的"canglaoshi"对应着{1}。

**Comment by qiwsir** [comment]
能不能直接修改，然后提交，我合并过去。这样就记录下这个错误是你指出的了。可否？

**Comment by HAOGRE** [comment]
ok

**Comment by HAOGRE** [comment]
done
