### ISSUE TITLE
`207.md` 中一句话有问题

### ISSUE THREAD

**Issue by youyaochi** [qiwsir/StarterLearningPython#12]
```
第二种定义方法，在类的前面写上这么一句：__metaclass__ == type，然后定义类的时候，就不需要在名字后面写(object)了。
```

这句好像不太对劲，试了下在类定义前加`__metaclass__ = type`也没有效果，放在类定义里就好用了。

**Comment by qiwsir** [comment]
推荐使用class ClassName(object)

**Comment by youyaochi** [comment]
是我弄错了...声明`__metaclass__ =type`后定义的类就是新类了，但是文章里写的是`__metaclass__ == type`.
