### ISSUE TITLE
关于122 三元运算符的补充

### ISSUE THREAD

**Issue by staticor** [qiwsir/StarterLearningPython#13]
除了 单行的 a if b else c以外, 也有其它的操作方式. 例如 and.. or 语句. 

[expression] and [on_true] or [on_false]

参考: 
http://www.pythoncentral.io/one-line-if-statement-in-python-ternary-conditional-operator/

http://stackoverflow.com/questions/394809/does-python-have-a-ternary-conditional-operator

**Comment by qiwsir** [comment]
从广义概念来说，是这样的。但是，在这里，我重点强调的是if...else模式，因为我个人认为，要跟一般的逻辑判断运算区别开。谢谢你提供此类补充。
