### ISSUE TITLE
Other Languages

### ISSUE THREAD

**Issue by Findlab** [qiwsir/StarterLearningPython#2]
If you translate english,that's really good for everybody.

**Comment by qiwsir** [comment]
You are right. But my english is pool.

**Comment by Findlab** [comment]
Okay,then

**Comment by staticor** [comment]
还好我看得懂中文 LOL. 

btw, maybe there have been some repos like this in other language.

**Comment by Findlab** [comment]
我希望我能理解 (google translate :) )

I'm sure there are some repos like this;but this repo is almost full of example

**Comment by qiwsir** [comment]
There are some very good Python books in English, for example 'Learning Python' and 'Programming Python'. Some part of 'Learning Python' was translate into Chinese, but I think it is not good as English version.
