### ISSUE TITLE
102.md 用内建函数id()可以查看每个对象的内存地址

### ISSUE THREAD

**Issue by wanghaisheng** [qiwsir/StarterLearningPython#22]
```
>>> id(3)
140396202092696
>>> id(3.0)
140396281118032
>>> id(3.00)
140396281118032
>>> id(3.000)
140396281118032
>>> id(3.01)
140396281118032
>>> id(3.001)
140396281118032
>>> id(3.011)
140396281118032
```
为什么 3.01  3.001 3.011会是一样的值呢
python -V
Python 2.7.10

**Comment by qiwsir** [comment]
请阅读：https://github.com/qiwsir/StarterLearningPython/blob/master/103.md

2015-08-20 23:01 GMT+08:00 wanghaisheng <notifications@github.com>:

> id(3)
> 140396202092696
> id(3.0)
> 140396281118032
> id(3.00)
> 140396281118032
> id(3.000)
> 140396281118032
> id(3.01)
> 140396281118032
> id(3.001)
> 140396281118032
> id(3.011)
> 140396281118032
>
> 为什么 3.01 3.001 3.011会是一样的值呢
> python -V
> Python 2.7.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/issues/22>.
>



-- 
*QiWei*

**Comment by wanghaisheng** [comment]
有没有103中那样类似解决除法的模块 来处理id这个问题呢

**Comment by Eric-M-Zhu** [comment]
id(任意浮点数) 的值都是一样的，我觉得这个语句应该是把浮点数赋值给一个临时变量，然后id(临时变量)。所以id(3.0)，id(4.0)等的结果都一样。

比如下面，开始id(3.0)和id(4.0)值都一样，再声明一个浮点数变量ff，ff的id值也是一样。再执行一句id(7.0)，id值就变了。前俩句，应该使用了同样的临时变量，声明ff时，把临时变量id给了ff，后面只能再分配一个临时变量了。

>>> id(3.0)
140303047617784
>>> id(3.1)
140303047617784
>>> ff = 6.0
>>> id(ff)
140303047617784
>>> id(7.0)
140303047617808

**Comment by wanghaisheng** [comment]
有一点明白了 谢谢
