### ISSUE TITLE
变量赋值的异常

### ISSUE THREAD

**Issue by wanghaisheng** [qiwsir/StarterLearningPython#23]
问 
在109-113.md中大量出现了如下的情况，是笔误还是有意为之，望解答
```
>>> all_users
['python', 'http://', 'qiwsir', 'github', 'io', 'algorithm']
```
为什么不是
```
>>> all_users = 
['python', 'http://', 'qiwsir', 'github', 'io', 'algorithm']
```

**Comment by qiwsir** [comment]
all_users是不是已经存在的变量？不是赋值。

2015-08-24 22:13 GMT+08:00 wanghaisheng <notifications@github.com>:

> 问
> 在109-113.md中大量出现了如下的情况，是笔误还是有意为之，望解答
>
> >>> all_users
> ['python', 'http://', 'qiwsir', 'github', 'io', 'algorithm']
>
> 为什么不是
>
> >>> all_users =
> ['python', 'http://', 'qiwsir', 'github', 'io', 'algorithm']
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/issues/23>.
>



-- 
*QiWei*

**Comment by wanghaisheng** [comment]
@qiwsir  比如109.md 最后一个示例中的b 112.md中的第一个例子中的la

**Comment by qiwsir** [comment]
109.md中的最后一个示例中的b，已经在前面做了赋值 b=a.title()

**Comment by wanghaisheng** [comment]
如果你指的是
```
>>> b = a.title()     #这样就把所有单词的第一个字母转化为大写
>>> b
'This Is A Book'
```
那最后的例子里你写的是
```
>>> b
'www.itdiffer.com'
```

**Comment by qiwsir** [comment]
因为我在写教程的过程中，中间要做调试。所以，变量值会变化。为了说明后面操作的变量值是什么，我一般要在示例开始，把已经有的变量值显示出来，比如你刚才说的>>>b，这样主要是告诉读者，现在b的变量值已经是什么了。至于如何来的，一般就比较简单，不用赘述了。

2015-08-25 13:58 GMT+08:00 wanghaisheng <notifications@github.com>:

> 如果你指的是
>
> >>> b = a.title()     #这样就把所有单词的第一个字母转化为大写
> >>> b
> 'This Is A Book'
>
> 那最后的例子里你写的是
>
> >>> b
> 'www.itdiffer.com'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/issues/23#issuecomment-134489405>
> .
>



-- 
*QiWei*

**Comment by wanghaisheng** [comment]
这样说就易于理解了，如果不追求严谨的话
