### ISSUE TITLE
无法加载js脚本

### ISSUE THREAD

**Issue by lln133208** [qiwsir/StarterLearningPython#24]
您好，您的教程写得很好，自己正在一步一步学习python，目前学习到使用tornado开发网站这里碰到一个问题，希望得到您的解答，谢谢。

自己对前端的东西不是很懂，下载了jQuery库后不知道如何使用，在官网下载1.11.4版本，解压后其中有很多js脚本和css文件，js脚本有`jquery-ui.js`， `jquery-ui.min.js`，按照您的教程中所讲，我将第二个脚本复制到我的tornado项目的`statics/js/`目录下，其余部分也都是按照您的教程来做的，运行`server.py`之后，使用chrome浏览器访问`127.0.0.1：8000`后，发现无法交互，服务器那边提示无法打开js文件。

我核对了js脚本的目录和权限，都没有问题。

**Comment by lln133208** [comment]
> 您好，您的教程写得很好，自己正在一步一步学习python，目前学习到使用tornado开发网站这里碰到一个问题，希望得到您的解答，谢谢。
> 
> 自己对前端的东西不是很懂，下载了jQuery库后不知道如何使用，在官网下载1.11.4版本，解压后其中有很多js脚本和css文件，js脚本有jquery-ui.js， jquery-ui.min.js，按照您的教程中所讲，我将第二个脚本复制到我的tornado项目的statics/js/目录下，其余部分也都是按照您的教程来做的，运行server.py之后，使用chrome浏览器访问127.0.0.1：8000后，发现无法交互，服务器那边提示无法打开js文件。
> 
> 我核对了js脚本的目录和权限，都没有问题。

如果我不使用**static_url**函数，而是直接使用js脚本的绝对路径，服务器不会提醒说打不开js脚本，得到Http code是404，依然是找不到该脚本。

**Comment by qiwsir** [comment]
你使用浏览器调试一下，看看报错信息。另外，写一个静态网页，使用js，试试。特别注意路径写法。

在 2015年9月11日 下午3:14，RenYuan <notifications@github.com>写道：

> 您好，您的教程写得很好，自己正在一步一步学习python，目前学习到使用tornado开发网站这里碰到一个问题，希望得到您的解答，谢谢。
>
> 自己对前端的东西不是很懂，下载了jQuery库后不知道如何使用，在官网下载1.11.4版本，解压后其中有很多js脚本和css文件，js脚本有jquery-ui.js，
> jquery-ui.min.js，按照您的教程中所讲，我将第二个脚本复制到我的tornado项目的statics/js/目录下，其余部分也都是按照您的教程来做的，运行server.py之后，使用chrome浏览器访问127.0.0.1：8000后，发现无法交互，服务器那边提示无法打开js文件。
>
> 我核对了js脚本的目录和权限，都没有问题。
>
> 如果我不使用*static_url*函数，而是直接使用js脚本的绝对路径，服务器不会提醒说打不开js脚本，得到Http
> code是404，依然是找不到该脚本。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/issues/24#issuecomment-139470166>
> .
>



-- 
*QiWei*

**Comment by lln133208** [comment]
> 你使用浏览器调试一下，看看报错信息。另外，写一个静态网页，使用js，试试。特别注意路径写法。

搞定了，之前下载的是jqueryui，我换成jquery后好了，google一下，还是有区别的啊。谢谢啊
