### ISSUE TITLE
章节: 上下文管理器 中的nested方法的问题

### ISSUE THREAD

**Issue by theJian** [qiwsir/StarterLearningPython#52]
学的时候我发现我的环境中没有nested方法, 查了一下, 发现这个方法已经被移除了, 原因是nested方法存在一个问题 https://docs.python.org/2/library/contextlib.html#contextlib.nested

既然这样的话, nested方法的那一小节是否还有存在必要.

**Comment by qiwsir** [comment]
我也注意到过那个文档。也计划删除了。但是，考虑到曾经有朋友拿出以往的代码，问过这个问题，所有就放上了，暂时没有删掉。后面我再进行修订的时候，有可能考虑删掉。因为现在正在修改部分内容。并且会逐渐过渡到py3。
