### ISSUE TITLE
105.md里的错别字吧

### ISSUE THREAD

**Issue by domino-jiang** [qiwsir/StarterLearningPython#58]
所谓语句，就是告诉程序要做什么事情。程序就是有各种各样的语句组成的。这条语句，又有一个名字，叫做**_复制语句_**。19+2*4-8/2是一个表达式，最后要计算出一个结果，这个结果就是一个对象（又遇到了对象这个术语。在某些地方的方言中，把配偶、男女朋友也称之为对象，“对象”是一个应用很广泛的术语）。=不要理解为数学中的等号，它的作用不是等于，而是完成赋值语句中“赋值”的功能。a就是变量。这样就完成了一个赋值过程。

应该是“赋值语句”而不是复制语句吧

**Comment by domino-jiang** [comment]
还有一处

当运行.py文件的时候，Python会通过编译器，将它编译为.pyc文件，然后这个文件就在一个名为虚拟机的东西上运行，这个所谓的虚拟机是专门为Python**_涉及_**的，正是因为有了虚拟机，使得Python是跨平台的，也就是说你写的Python程序可以不经过修改而在不同才做系统上运行。

应该是“专门为 Python 设计的”吧？

**Comment by qiwsir** [comment]
是的。我正在修改这个教程，把python 3也涵盖进去。你指出的问题，我会修改。谢谢。
