### ISSUE TITLE
212.md中，有个笔误！

### ISSUE THREAD

**Issue by bells** [qiwsir/StarterLearningPython#6]
“这个其实是指向了类属性中的Spring.season，至此，我们其实还没有建立任何类属性呢。下面就建立一个类属性：“
应该是：
”这个其实是指向了类属性中的Spring.season，至此，我们其实还没有建立任何实例属性呢。下面就建立一个实例属性：“

**Comment by qiwsir** [comment]
Yes, You are right. Thank you very much.
